name: Auto Update Changelog

on:
  push:
    paths:
      - 'challenges/**'
      - 'generate_readme.py'
      - 'update_changelog.py'
      - '.github/workflows/update-changelog.yml'

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Run Changelog Updater
      run: python update_changelog.py

    - name: Commit and Push Changelog
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add CHANGELOG.md
        git commit -m "Auto-update CHANGELOG.md" || echo "No changes to commit"
        git pull --rebase origin main || echo "No upstream changes"
        git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
